# Generated by Django 3.1.13 on 2021-08-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20210808_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowreceipt',
            name='date_borrowed',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='borrowreceipt',
            name='date_to_return',
            field=models.DateField(),
        ),
    ]
