# Generated by Django 3.1.13 on 2021-08-09 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20210809_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowreceipt',
            name='return_receipt',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='books.returnreceipt'),
        ),
    ]
